// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnw4UIBTMET2boNJ3atQMFMxtKkWV6F4I',
    appId: '1:236668948248:web:7e497d190047157c76186d',
    messagingSenderId: '236668948248',
    projectId: 'local-bus-f10b6',
    authDomain: 'local-bus-f10b6.firebaseapp.com',
    storageBucket: 'local-bus-f10b6.firebasestorage.app',
    measurementId: 'G-H4ZPN5FMWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHdM159j77KEh57xL57g7yqkcNu-j1o6M',
    appId: '1:236668948248:android:a21c3cfece55268876186d',
    messagingSenderId: '236668948248',
    projectId: 'local-bus-f10b6',
    storageBucket: 'local-bus-f10b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrcrkNdKswyefY9-yZQlzzJrl5o6IlEE',
    appId: '1:236668948248:ios:4756bb320979b57e76186d',
    messagingSenderId: '236668948248',
    projectId: 'local-bus-f10b6',
    storageBucket: 'local-bus-f10b6.firebasestorage.app',
    androidClientId: '236668948248-4o47ele25rh655k7s7sv3641atdmp6h5.apps.googleusercontent.com',
    iosClientId: '236668948248-8u4vmrkpel1sa8tg2j7cmbfva5k2k61v.apps.googleusercontent.com',
    iosBundleId: 'com.example.areaControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrcrkNdKswyefY9-yZQlzzJrl5o6IlEE',
    appId: '1:236668948248:ios:4756bb320979b57e76186d',
    messagingSenderId: '236668948248',
    projectId: 'local-bus-f10b6',
    storageBucket: 'local-bus-f10b6.firebasestorage.app',
    androidClientId: '236668948248-4o47ele25rh655k7s7sv3641atdmp6h5.apps.googleusercontent.com',
    iosClientId: '236668948248-8u4vmrkpel1sa8tg2j7cmbfva5k2k61v.apps.googleusercontent.com',
    iosBundleId: 'com.example.areaControl',
  );
}
